
[env]
TERM = "xterm-256color"

# [shell]
# program = "zellij"
# args = ["-l", "-c", "zellij attach --index 0 || zellij -s dev"]

[terminal.shell]
args = ["-l", "-c", "zellij attach -c dev"]
program = "/bin/zsh"

[window]
option_as_alt = "OnlyLeft"
padding.x = 10
padding.y = 10

decorations = "buttonless"
dynamic_padding = false

[font]
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
bold = { family = "FiraCode Nerd Font Mono", style = "Bold" }
italic = { family = "FiraCode Nerd Font Mono", style = "Italic" }
# normal.family = "FiraCode Nerd Font Mono"

size = 14

[general]
import = ["~/.config/alacritty/themes/themes/nightfly.toml"]

[terminal]
